// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using projekat_finalWebAPI.Models;

namespace projekat_finalWebAPI.Migrations
{
    [DbContext(typeof(ProdavnicaContext))]
    [Migration("20210823071614_V1")]
    partial class V1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("projekat_finalWebAPI.Models.Kategorija", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("naziv")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("naziv");

                    b.Property<string>("opis")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("opis");

                    b.Property<int?>("prodavnicaid")
                        .HasColumnType("int");

                    b.Property<string>("slika")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("slika");

                    b.HasKey("id");

                    b.HasIndex("prodavnicaid");

                    b.ToTable("Kategorija");
                });

            modelBuilder.Entity("projekat_finalWebAPI.Models.Komponenta", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("cena")
                        .HasColumnType("int")
                        .HasColumnName("cena");

                    b.Property<int?>("kategorijaid")
                        .HasColumnType("int");

                    b.Property<int>("kolicina")
                        .HasColumnType("int")
                        .HasColumnName("kolicina");

                    b.Property<string>("naziv")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("naziv");

                    b.Property<string>("slika")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("slika");

                    b.HasKey("id");

                    b.HasIndex("kategorijaid");

                    b.ToTable("Komponenta");
                });

            modelBuilder.Entity("projekat_finalWebAPI.Models.Prodavnica", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("id");

                    b.ToTable("Prodavnica");
                });

            modelBuilder.Entity("projekat_finalWebAPI.Models.Kategorija", b =>
                {
                    b.HasOne("projekat_finalWebAPI.Models.Prodavnica", "prodavnica")
                        .WithMany("kategorije")
                        .HasForeignKey("prodavnicaid");

                    b.Navigation("prodavnica");
                });

            modelBuilder.Entity("projekat_finalWebAPI.Models.Komponenta", b =>
                {
                    b.HasOne("projekat_finalWebAPI.Models.Kategorija", "kategorija")
                        .WithMany("komponente")
                        .HasForeignKey("kategorijaid");

                    b.Navigation("kategorija");
                });

            modelBuilder.Entity("projekat_finalWebAPI.Models.Kategorija", b =>
                {
                    b.Navigation("komponente");
                });

            modelBuilder.Entity("projekat_finalWebAPI.Models.Prodavnica", b =>
                {
                    b.Navigation("kategorije");
                });
#pragma warning restore 612, 618
        }
    }
}
